### ISSUE TITLE
Builds fail with nixpkgs/nixos-22.11

### ISSUE THREAD

**Issue by rskew** [axelf4/nix-rebar3#1]
Hello, thanks for `nix-rebar3`!

When moving from "nixpkgs/nixos-22.05" to "nixpkgs/nixos-22.11" my build started failing during `installPhase` with `consumeEntire(): ERROR: Input null bytes, won't process`, due to `$out/rel/*/erts-*/bin/erl` now being a binary file (crashing `substituteInPlace` here https://github.com/axelf4/nix-rebar3/blob/master/default.nix#L147).

Not running `substituteInPlace` for binary files fixes the problem:
```
                if [ -z "$(file $f -b --mime | grep 'charset=binary')" ]; then
                  substituteInPlace "$f" --replace ${erlang}/lib/erlang "''${f%/erts-*/bin/*}"
                fi
```
however this feels clunky, there's probably a more appropriate solution that I'm not seeing due to my lack of understanding of erlang releases and nix-rebar3 (or maybe my project is mis-configured in some other way).

I haven't managed to find how/why the file is now binary rather than ascii. With nixos-22.11, rebar3 version 3.20.0 is used, whereas nixos 22.05 uses rebar3 3.18.0. Both nixos 22.11 and 22.05 use Erlang/OTP 24 and Erts 12.3.2.5.

I've created a small reproducible example here https://github.com/rskew/nix-rebar3-bug-demo

Cheers :)

**Comment by axelf4** [comment]
Looks like relx which was bumped now overwrites the `erl` shell script with the `dyn_erl` executable, (for which no references need to be removed). Though erlware/relx@62c92f3cca2b544b63c1305bf18df75f8be85213 which seems to have made the change was already included in relx 4.0.0, and specially also in rebar3 3.18.0, so I am not sure what actually triggered the difference.

Something like
```diff
diff --git a/default.nix b/default.nix
index db01192..ffeb439 100644
--- a/default.nix
+++ b/default.nix
@@ -143,7 +143,9 @@ in {
             ''
               find $out/rel/*/bin -type f -executable -exec ln -st $out/bin {} +
               # Remove references to erlang to reduce closure size
-              for f in $out/rel/*/erts-*/bin/{erl,start}; do
+              for f in $out/rel/*/erts-*/bin/${if
+                # Newer versions of relx use dyn_erl instead of the erl shell script
+                (lib.versionAtLeast rebar3.version "3.19.0") then "start" else "{erl,start}"}; do
                 substituteInPlace "$f" --replace ${erlang}/lib/erlang "''${f%/erts-*/bin/*}"
               done
             ''}
```
is the most robust fix I can think of. Will push a commit later if it looks good to you.

**Comment by rskew** [comment]
Looks good to me, thanks :)

**Comment by rskew** [comment]
Just bumping this :)
